# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Github Mobile' do
  
  use_frameworks!
  pod 'Alamofire'
  pod 'OAuthSwift','~> 1.2.2'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Charts'
  pod 'ChartsRealm'
end
